# permissions for end users to edit restapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: restapi-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo-operator
    app.kubernetes.io/part-of: demo-operator
    app.kubernetes.io/managed-by: kustomize
  name: restapi-editor-role
rules:
- apiGroups:
  - middleware.ibm.demo.com
  resources:
  - restapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middleware.ibm.demo.com
  resources:
  - restapis/status
  verbs:
  - get
